services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - drumscript

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://drumuser:drumpass@postgres:5432/drumtranscribe
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      # AWS S3 Configuration (optional - set in .env file)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - upload_data:/app/uploads
    networks:
      - drumscript

  backend_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.tasks.transcription", "worker", "--loglevel=info", "--concurrency=1", "--queues=backend"]
    environment:
      - DATABASE_URL=postgresql://drumuser:drumpass@postgres:5432/drumtranscribe
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      # AWS S3 Configuration (optional - set in .env file)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - upload_data:/app/uploads
    networks:
      - drumscript

  ml_worker:
    build:
      context: ./ml_worker
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://drumuser:drumpass@postgres:5432/drumtranscribe
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # AWS S3 Configuration (optional - set in .env file)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    depends_on:
      - redis
      - postgres
    volumes:
      - ./ml_worker:/app
      - upload_data:/app/uploads
      - model_cache:/app/models
    networks:
      - drumscript

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=drumtranscribe
      - POSTGRES_USER=drumuser
      - POSTGRES_PASSWORD=drumpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - drumscript

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - drumscript

volumes:
  postgres_data:
  redis_data:
  upload_data:
  model_cache:

networks:
  drumscript:
    driver: bridge